function_name: HAPPYCAT
function:
  _target_: opfunu.cec_based.cec2014.F132014
  ndim: 10
evaluate: "evaluate"
num_variables: 10
start_interval: -100
end_interval: 100
evolutions_number: 10
optuna_n_trials: 30
param_ranges:
  population_size:
    - 100
    - 600
  num_generations:
    - 100
    - 600
  selection_strategy:
    - "TOURNAMENT"
    - "ROULETTE"
  elite_strategy:
    - True
  elite_size:
    - 2
    - 20
  tournament_size:
    - 2
    - 5
  selection_size:
    - 10
    - 50
  crossover_strategy:
    - "ALFA"
    - "ALFA_BETA"
    - "ARITHMETIC"
    - "LINEAR"
  mutation_strategy:
    - "UNIFORM"
    - "GAUSSIAN"
  crossover_probability:
    - 0.7
    - 0.9
  mutation_probability:
    - 0.05
    - 0.3
